# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            DoomDoom's IT LAB
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://www.instagram.com/doooomdoom/" target="_blank">@doooomdoom</a>.'
url:              "https://dhdh3311.github.io"
baseurl:          ""

author:
  name:           "doooomdoom"
  url:            "https://www.instagram.com/doooomdoom/"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

remote_theme : poole/hyde